apiVersion: v1
kind: ConfigMap
metadata:
  name: greetings
data:
  NAME: SantaAnna

---

apiVersion: v1
kind: Secret
metadata:
  name: greetings-secret
type: Opaque
data:
  redisPassword: c2ltcGxlUGFzcw==  # Base64 encoded password  echo -n "simplePass" | base64
